version: "3"

services: 
  nginx:
    container_name: portfolio_nginx
    restart: unless-stopped
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    ports:
      - 3000:80
    volumes:
      - ./docker/nginx/development:/etc/nginx/conf.d
      - staticfiles:/app/staticfiles

volumes:
  staticfiles: